# Python

1.Write a program using list comprehension to find primes 
in range 2 to 100.

In [1]:
prime=[x for x in range(2, 100) if x>1 if all(x % y != 0 for y in range(2, x))]

In [3]:
print(prime)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


2.Write a function to reverse a string

string='reverse a string'

In [8]:
def rev(st):
    return s[::-1]
s="reverse a string"

In [9]:
print(rev(s))

gnirts a esrever


3.Write a program to extract the words from the given list which have their first character in uppercase. Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']

Output: ['Monday', 'Sunday', 'Saturday'

In [11]:
Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']
out=[]
for i in Days:
    if  i.istitle():
        out.append(i)

In [12]:
print(out)

['Monday', 'Sunday', 'Saturday']


4.Write a program to extract the year part from the dates in 
the given list.

Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']

Output: ['1997','2011','1993','2020']

In [51]:
Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']
out=[]
#outt=[]

In [52]:
for i in Batch:
    j=i[6:]
    out.append(j)

In [29]:
#for i in Batch:
#    j=i[-4::]
#    outt.append(j)

In [53]:
#print(outt)
print(out)

['1997', '2011', '1993', '2020']


5.Write a program swap the keys to values and values to keys of the given dictionary. 

Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4} 

Output: {1:'Data Science',2:'Machine Learning', 3:'SQL', 4:'Big Data'}

In [48]:
Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4}
new_m={}
#new_j={}

In [49]:
for i in Module.items():
    new_m[i[1]]=i[0]

In [45]:
#for i,j in Module.items():
#    new_j.update({j:i})
    
#print(new_j)    

In [50]:
print(new_m)

{1: 'Data Science', 2: 'Machine Learning', 3: 'SQL', 4: 'Big Data'}


6.Write a program to count the number of elements in the string (given by the user) that are not present in the 'my_string'. 

Do not count the white spaces.

my_string = 'Data Science'

In [54]:
my_string = 'Data Science'
strr=input("Enter any String : ")
new_str=strr.replace(" ","")
a=0

Enter any String : bhaskar bora 


In [55]:
for i in new_str.lower():
    if i not in my_string.lower():
        a=a+1

In [56]:
print(a)

7


7.Define a function to check whether a number is in a range (1000,10000) or not.

In [57]:
def check(n):
    if n>=1000 and n<=10000:
        print("In Range")
    else:
        print("Not In Range")

In [58]:
check(9999)

In Range


8.Write a program to calculate the sum of all elements in the list.

test_score = [10, 32, 23, 14, 25]

In [59]:
test_score = [10, 32, 23, 14, 25]
total=0

In [60]:
for i in test_score:
    total=total+i

In [61]:
print(total)

104


9.Replace all even numbers in the array with -1.

Use the array given below num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [6]:
import numpy as np
num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [7]:
num_array[num_array%2 == 0] = -1 

In [8]:
num_array

array([-1, 21, -1, 13, -1, 45, -1, -1, -1, -1, 65, -1, -1])

10.Find the minimum value along each of the rows. 

Create a 2D Numpy array from list of lists 

Score = np.array([[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]])

In [9]:
Score = np.array([[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]])


In [10]:
Score

array([[210, 402, 383],
       [140, 375, 106],
       [140, 125, 217],
       [292, 240, 295]])

In [11]:
Score.min(axis=1)

array([210, 106, 125, 240])

In [12]:
Score = Score.reshape(2,6)
print(Score)
print(Score.ndim)

[[210 402 383 140 375 106]
 [140 125 217 292 240 295]]
2
